name: monan_post
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - cartopy=0.18.0
  - holoviews=1.14.9
  - hvplot=0.8.0
  - jupyter=1.0.0
  - jupyterlab=3.4.5
  - matplotlib=3.5.2
  - netcdf4=1.5.8
  - numpy=1.21.5
  - pandas=1.3.5
  - pip=21.2.2
  - python=3.7.13
  - xarray=0.20.2
  - pip:
      - aiohttp==3.8.4
      - intake==0.6.6
      - intake-xarray==0.6.0
      - panel==0.14.3
      - panel-modal==0.2.0
      - xgrads==0.2.3
      - zarr==2.12.0
